source "https://rubygems.org"

gemspec

gem "google-style", "~> 1.31.0"
gem "minitest", ">= 5.24", "< 7"
gem "minitest-autotest", "~> 1.1"
gem "minitest-focus", "~> 1.4"
gem "minitest-rg", "~> 5.3"
gem "redcarpet", "~> 3.0"
gem "yard", "~> 0.9"
